"""For automatically testing all the combinations"""

import os

TEST_DATA = [
    {'test_num': '08-01',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base',
     'ansible_state': 'absent'},
    {'test_num': '08-02',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base',
     'ansible_state': 'build-dep'},
    {'test_num': '08-03',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base',
     'ansible_state': 'fixed'},
    {'test_num': '08-04',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base',
     'ansible_state': 'latest'},
    {'test_num': '08-05',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base',
     'ansible_state': 'present'},
    {'test_num': '08-06',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'absent'},
    {'test_num': '08-07',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'build-dep'},
    {'test_num': '08-08',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'fixed'},
    {'test_num': '08-09',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'latest'},
    {'test_num': '08-10',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'present'},
    {'test_num': '08-11',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'absent'},
    {'test_num': '08-12',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'build-dep'},
    {'test_num': '08-13',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'fixed'},
    {'test_num': '08-14',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'latest'},
    {'test_num': '08-15',
     'os': 'jesse',
     'previously_installed': 'no',
     'previous_version': 'N/A',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'present'},
    {'test_num': '08-16',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base',
     'ansible_state': 'absent'},
    {'test_num': '08-17',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base',
     'ansible_state': 'build-dep'},
    {'test_num': '08-18',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base',
     'ansible_state': 'fixed'},
    {'test_num': '08-19',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base',
     'ansible_state': 'latest'},
    {'test_num': '08-20',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base',
     'ansible_state': 'present'},
    {'test_num': '08-21',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'absent'},
    {'test_num': '08-22',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'build-dep'},
    {'test_num': '08-23',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'fixed'},
    {'test_num': '08-24',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'latest'},
    {'test_num': '08-25',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'present'},
    {'test_num': '08-26',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'absent'},
    {'test_num': '08-27',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'build-dep'},
    {'test_num': '08-28',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'fixed'},
    {'test_num': '08-29',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'latest'},
    {'test_num': '08-30',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'present'},
    {'test_num': '08-31',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base',
     'ansible_state': 'absent'},
    {'test_num': '08-32',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base',
     'ansible_state': 'build-dep'},
    {'test_num': '08-33',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base',
     'ansible_state': 'fixed'},
    {'test_num': '08-34',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base',
     'ansible_state': 'latest'},
    {'test_num': '08-35',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base',
     'ansible_state': 'present'},
    {'test_num': '08-36',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'absent'},
    {'test_num': '08-37',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'build-dep'},
    {'test_num': '08-38',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'fixed'},
    {'test_num': '08-39',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'latest'},
    {'test_num': '08-40',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base=1.3.3.5-4',
     'ansible_state': 'present'},
    {'test_num': '08-41',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'absent'},
    {'test_num': '08-42',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'build-dep'},
    {'test_num': '08-43',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'fixed'},
    {'test_num': '08-44',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'latest'},
    {'test_num': '08-45',
     'os': 'jesse',
     'previously_installed': 'yes',
     'previous_version': '1.3.3.5-4+deb8u7',
     'package_name': '389-ds-base=1.3.3.5-4+deb8u7',
     'ansible_state': 'present'},
]


PLAYBOOK_TEMPLATE = """
---
- name: Demo Playbook
  hosts: localhost
  tasks:
    - debug: msg="Ansible is working."

- name: Run test
  hosts: localhost
  tasks:
    - name: Run this test case
      sapt:
        name: {package_name}
        state: {ansible_state}
      become: yes
"""


TESTING_ROW_FORMAT = ("|{test_num:5s}|{os:6s}"
                      "|   {previously_installed:8s} "
                      "| {previous_version:17s}| {package_name:29s}"
                      "| {ansible_state:15s}")


def testing_table():
    """Print testing table in Human Format to Standard Out"""
    print("|Test |      | Previously |")
    print("|Num  |  OS  | installed? | Previous Version |"
          " Package Name                 |  Ansible State")
    print("+-----+------+------------+------------------+"
          "------------------------------+----------------")
    for row in TEST_DATA[30:]:
        print(TESTING_ROW_FORMAT.format(**row))

def test_suite():
    """Begin Test Suite"""
    for row in TEST_DATA[30:]:
        #row = TEST_DATA[22]
        with open("./RESULTS.txt", "a") as results_f:
            results_f.write("%s\n" % ("="*75))
            results_f.write("|{test_num:5s}|{os:6s}"
                            "|   {previously_installed:8s} "
                            "| {previous_version:17s}| {package_name:29s}"
                            "| {ansible_state:15s}".format(**row))
        playbook = PLAYBOOK_TEMPLATE.format(**row)
        with open("run_test_case.yml", "w") as playbook_f:
            playbook_f.write(playbook)
        os.system('make test_run')
        #if row['previous_version'] == '1.3.3.5-4+deb8u7':
        #    break


#testing_table()
test_suite()
